# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YouUp < Formula
  desc ""
  homepage "https://github.com/guifeliper/you-up"
  version "0.3"

  on_macos do
    url "https://github.com/guifeliper/you-up/releases/download/v0.3/you-up_0.3_darwin_all.tar.gz"
    sha256 "23e56144bd1f6ddddfb4110bdd192cdaa7715fde738856f51857f8f04a748bc5"

    def install
      bin.install "you-up"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guifeliper/you-up/releases/download/v0.3/you-up_0.3_linux_arm64.tar.gz"
      sha256 "7cb84183f2aeb23a7ec0c95b5795d160a2b0db11dcd5379dc83216168b3de540"

      def install
        bin.install "you-up"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/guifeliper/you-up/releases/download/v0.3/you-up_0.3_linux_amd64.tar.gz"
      sha256 "8fbc469ccaa803b1c60ef34b01d1d2ff177069a7e826d118f52de4717837e8ec"

      def install
        bin.install "you-up"
      end
    end
  end
end
