# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YouUp < Formula
  desc ""
  homepage "https://github.com/guifeliper/you-up"
  version "0.2"

  on_macos do
    url "https://github.com/guifeliper/you-up/releases/download/v0.2/you-up_0.2_darwin_all.tar.gz"
    sha256 "89164b5dfa934f255a76dc668e0aa8db9162fb72522a6701a22d6f761b257e81"

    def install
      bin.install "you-up"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guifeliper/you-up/releases/download/v0.2/you-up_0.2_linux_arm64.tar.gz"
      sha256 "1c00d01cc642a170ed83692635912d4fc73d081bab5e753372aea43755dab285"

      def install
        bin.install "you-up"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/guifeliper/you-up/releases/download/v0.2/you-up_0.2_linux_amd64.tar.gz"
      sha256 "bb3e4a519a9ab66b4fae37f1ce70fb35dee86cff10740ec7117f31c037938b46"

      def install
        bin.install "you-up"
      end
    end
  end
end
